### ISSUE TITLE
Extension create account fades out after alt-tabbing

### ISSUE THREAD

**Issue by modernlearner** [PureStake/algosigner#195]
I'm trying to create a new account through the AlgoSigner Chrome extension and in both Chrome and Brave, whenever I alt-tab to be able to write the password down in a password manager, the extension pop-up fades out so I have to begin the process all over again.

Is there an alternative way for me to create an account that can be used by AlgoSigner? The browser's behaviour is blocking me from creating an account and I'm sure it would block potential users of our dApp from using AlgoSigner.

**Comment by nullun** [comment]
Having experienced the same issue, I completed the account setup process by copying the mnemonic down then using the "Import existing account" process and using my given mnemonic to create the account. Not ideal, but it gets you into a usable state where you can then use the extension.

**Comment by purestaketdb** [comment]
It will work under some base cases to alt-tab out and back, but for others it goes away and the stage is lost (as you are experiencing). We can't control the extension window fading out, but, we could keep your place if we persist more into memory. That change is under discussion with our security auditor as we clearly don't want people getting frustrated there.

In the meantime the simple workaround is to copy the mnemonic out, store it safely, and then import the account back in instead of going back into the create new account flow as nullun points out.

**Comment by modernlearner** [comment]
I'll try the workaround, thanks!

I was checking what MyEtherWallet and the built-in crypto wallet in Brave browser does and it looks like they open a new tab with a different page to setup new accounts. However, I'm not sure what mechanism that uses.
