### ISSUE TITLE
Adding appOnComplete and appArgs to an application call crashes AlgoSigner during sign

### ISSUE THREAD

**Issue by Lumene98** [PureStake/algosigner#216]
The application call is 
```javascript
{
      type: 'appl',
      from: userAddress,
      appIndex: environment.appId,
      appOnComplete: 0, // 0 == NoOp
      appArgs: appArgs,
      fee: txParams.fee,
      firstRound: txParams['last-round'],
      lastRound: txParams['last-round'] + 1000,
      genesisID: txParams['genesis-id'],
      genesisHash: txParams['genesis-hash'],
}
```
And the encodedAppArgs are 
```javascript
const appArgs = [
     new Uint8Array(Buffer.from('da')),
];
```

![image](https://user-images.githubusercontent.com/26761348/114908819-c4070780-9e1c-11eb-96fc-5b84dd194546.png)
![image](https://user-images.githubusercontent.com/26761348/114908834-c79a8e80-9e1c-11eb-9610-5ef3c86e63d1.png)

**Comment by PureBrent** [comment]
The circular error seen here is due to an issue in the format a base64 field. The appArgs should each be a string value that is base64. 

In this case it looks like the passed value is an array. If the value being created is 'utf-8' as it appears, then it will need to be cast to base64 for each argument or element.
