### ISSUE TITLE
Request an extension support for firefox or safari

### ISSUE THREAD

**Issue by Vidhyanandcs** [PureStake/algosigner#219]
It would be great if there is an extension available for safari or firefox. Thus we can give a choice to the end user on which browser they can use to visit our dApp. Metamask is having a firefox and chrome extension. Limiting us to one browser may negatively effect adoption.

![Capture2](https://user-images.githubusercontent.com/11901913/117402604-5a15e580-af24-11eb-9ab1-83eb1b14ea89.JPG)

**Comment by nullun** [comment]
I believe PureStake are intending on releasing an AlgoSigner Firefox extension, however haven't announced any timeline or roadmap as of yet. With the release of some very interesting projects in the near future I do hope there is news on this sooner rather than later.

I would also expect those browser market share stats to be quite different for this space given worldwide use vs people in crypto/defi. But I have no evidence for that, it's just a hunch.

**Comment by Vidhyanandcs** [comment]
Thank you. Browser market share stats may be different as of now in this space. But things will be different once dApps become more mainstream.
