### ISSUE TITLE
Is it possible to sign single transactions belonging to a group?

### ISSUE THREAD

**Issue by alessandrobessi** [PureStake/algosigner#334]
Hello, I'm trying to sign a transaction belonging to a group of two transactions. The first transaction has already been signed server-side, and I'm trying to sign the second one client-side using AlgoSigner, but I'm receiving this error: "The transaction group is incomplete or presented in a different order than when it was created.".

By looking at the code (https://github.com/PureStake/algosigner/blob/323e0be938f9e50a7344129f265b5820744301d7/packages/test-project/tests/dapp-signtxn.test.js#L165) I suppose is not possible to sign single transactions belonging to a group.

Am I right?

**Comment by janmarcano** [comment]
Hi @alessandrobessi, in order to sign the second transaction using AlgoSigner, you would need to provide the first _**unsigned**_ transaction as well. This is for security purposes so that the user can look at the whole group of transactions and be 100% aware of what they're signing.

Since the first transaction is already being signed on your end, you can use the `signers` field to tell AlgoSigner that you're providing the transaction only for verification purposes and not to sign it. You can find an example of this in [the documentation](https://github.com/PureStake/algosigner/blob/develop/docs/dApp-integration.md#atomic-transactions).

I'm closing the issue for now, but feel free to post any further questions here and I'll get back to you.
