### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by anchorite01** [PureStake/algosigner#449]
Request:
`curl -X 'GET'   'https://mainnet-algorand.api.purestake.io/idx2/v2/blocks/23593532'   -H 'accept: application/json'   -H 'x-api-key: xxxx'

Response:
`{"message": "Internal server error"}`

What causes this?

**Comment by lionDEVa** [comment]
It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Algorand Live Support](algorrand-dev.com)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by purestaketdb** [comment]
Although this is not strictly speaking where the API is supported (we have a channel on the Algorand Discord server for both AlgoSigner and the API that is checked regularly) - the issue is the block size is so large that the API Gateway in AWS rejects it. The team is working on a resolution to the issue now.
